version: '3.7'

services:
    web:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - ${EXPOSED_PORT}:80
        restart: always
        env_file:
          - .env
